(defun combine-max2(lst1 lst2)
	(cond ((null lst1) lst2)
	      ((null lst2) lst1)
	      ((> (car lst1) (car lst2))(cons (car lst1) (combine-max2 (cdr lst1) (cdr lst2))))
	      (t (cons (car lst2) (combine-max2 (cdr lst1) (cdr lst2))))))
